# Generated by Django 3.1.5 on 2021-01-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tempat_lahir', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField(auto_now_add=True)),
                ('instansi', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
                ('input_kode_sekuriti', models.CharField(max_length=50)),
            ],
        ),
    ]
