# Generated by Django 3.1.5 on 2021-01-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userspns_1184077', '0002_auto_20210109_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='input_kode_sekuriti',
        ),
    ]
